import argparse
import random
from datetime import UTC, datetime, timedelta

from sqlalchemy import select

from app.core.config import settings
from app.core.database import SessionLocal
from app.core.security import get_password_hash
from app.models.enums import DepartmentEnum, PriorityEnum, RoleEnum
from app.models.task import Task
from app.models.user import User
from app.services.assignment_service import recompute_task_assignment


LOCATIONS = ["Mumbai", "Bengaluru", "Delhi", "Chennai", "Hyderabad", "Pune"]
PRIORITIES = [PriorityEnum.LOW, PriorityEnum.MEDIUM, PriorityEnum.HIGH, PriorityEnum.URGENT]
DEPARTMENTS = list(DepartmentEnum)


def ensure_seed_admins(db):
    defaults = [
        {
            "email": settings.seed_admin_email,
            "full_name": "Assessment Admin",
            "role": RoleEnum.ADMIN,
            "department": DepartmentEnum.OPERATIONS,
            "experience_years": 12,
            "location": "Bengaluru",
            "password": settings.seed_admin_password,
        },
        {
            "email": settings.seed_manager_email,
            "full_name": "Assessment Manager",
            "role": RoleEnum.MANAGER,
            "department": DepartmentEnum.FINANCE,
            "experience_years": 8,
            "location": "Mumbai",
            "password": settings.seed_manager_password,
        },
        {
            "email": "info@indusaction.org",
            "full_name": "Demo User",
            "role": RoleEnum.USER,
            "department": DepartmentEnum.IT,
            "experience_years": 5,
            "location": "Delhi",
            "password": "demo12345",
        },
    ]

    for item in defaults:
        existing = db.execute(select(User).where(User.email == item["email"])).scalar_one_or_none()
        if existing:
            existing.full_name = item["full_name"]
            existing.password_hash = get_password_hash(item["password"])
            existing.role = item["role"]
            existing.department = item["department"]
            existing.experience_years = item["experience_years"]
            existing.location = item["location"]
            existing.is_active = True
            existing.active_task_count = 0
            db.add(existing)
        else:
            db.add(
                User(
                    email=item["email"],
                    full_name=item["full_name"],
                    password_hash=get_password_hash(item["password"]),
                    role=item["role"],
                    department=item["department"],
                    experience_years=item["experience_years"],
                    location=item["location"],
                    is_active=True,
                    active_task_count=0,
                )
            )
    db.commit()


def seed_users(db, count: int) -> None:
    existing_users = db.execute(select(User.id)).scalars().all()
    if len(existing_users) >= count + 2:
        return

    batch: list[User] = []
    start_idx = len(existing_users) + 1
    for index in range(start_idx, start_idx + count):
        department = random.choice(DEPARTMENTS)
        batch.append(
            User(
                email=f"user{index}@example.com",
                full_name=f"Sample User {index}",
                password_hash=get_password_hash("user12345"),
                role=RoleEnum.USER,
                department=department,
                experience_years=random.randint(0, 12),
                location=random.choice(LOCATIONS),
                is_active=True,
                active_task_count=0,
            )
        )
    db.add_all(batch)
    db.commit()


def seed_tasks(db, count: int) -> None:
    existing_tasks = db.execute(select(Task.id)).scalars().all()
    if len(existing_tasks) >= count:
        return

    creator = (
        db.execute(
            select(User).where(User.role.in_([RoleEnum.ADMIN, RoleEnum.MANAGER])).order_by(User.id.asc())
        )
        .scalars()
        .first()
    )
    if not creator:
        raise RuntimeError("Seed users must include an admin or manager before seeding tasks")
    to_create = count - len(existing_tasks)
    new_tasks: list[Task] = []

    for index in range(1, to_create + 1):
        department = random.choice(DEPARTMENTS + [None])
        location = random.choice(LOCATIONS + [None])
        min_experience = random.choice([None, 0, 2, 4, 6])
        max_active = random.choice([None, 3, 5, 8])
        task = Task(
            title=f"Seed Task {len(existing_tasks) + index}",
            description="Autogenerated assessment seed task.",
            priority=random.choice(PRIORITIES),
            due_date=datetime.now(UTC) + timedelta(days=random.randint(1, 21)),
            created_by_id=creator.id,
            assignment_reason="Task queued for background eligibility computation.",
            rule_department=department,
            rule_location=location,
            rule_min_experience_years=min_experience,
            rule_max_active_tasks=max_active,
        )
        new_tasks.append(task)

    db.add_all(new_tasks)
    db.commit()

    task_ids = [task.id for task in new_tasks if task.id]
    for task_id in task_ids:
        recompute_task_assignment(db, task_id, "seed-data-load")


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed demo data for the task management system")
    parser.add_argument("--users", type=int, default=200)
    parser.add_argument("--tasks", type=int, default=500)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)
    db = SessionLocal()
    try:
        ensure_seed_admins(db)
        seed_users(db, args.users)
        seed_tasks(db, args.tasks)
    finally:
        db.close()


if __name__ == "__main__":
    main()
